### PR TITLE
Make WASI and w2c2_base.h compile on MSVC 4.0

### PR DESCRIPTION
**Pull request by SergioFLS**
Why MSVC 4.0 specifically? Mostly because it's the only compiler that I'm aware of that can target the RISC versions of Windows NT 4.0 (yes, there were official versions for MIPS, PowerPC and Alpha).

~~Generated code will still not compile with it though, as there's no `long long` type in MSVC4. You can replace all `LL` suffixes with `i64` though, around c.c:1049:~~
https://github.com/turbolent/w2c2/blob/22a9adeef081714e0d07ea62aa0ec734c6a5f99f/w2c2/c.c#L1047-L1050

~~The only reason that I didn't include it in this PR is that I wasn't able to find a way to add a type toggle switch while making the code pretty.~~ (UPDATE: Made a `W2C2_LL` macro, no need for this anymore.)

There's still stuff to do to get the generated code to work completely with MSVC4, such as finding workarounds to the following errors:
* `error C2520: conversion from unsigned __int64 to double not implemented, use signed __int64`
* `fatal error C1053: 'fXXXX' : function too large`

Also, while not exactly fatal, the endianness check fails on MIPS for some reason (untested on PowerPC and Alpha).

Those errors come from the Python example, although I was able to get the ls and Rust examples working from the current patches.

### CODE REVIEW

File: w2c2/w2c2_base.h [hunk 1]
```diff
@@ -185,6 +190,12 @@ typedef double F64;
 #define UNUSED
 #endif
 
+#if defined(_MSC_VER) && _MSC_VER <= 1000
+#define LLONG_MIN (-0x7fffffffffffffffi64-1)
```
Comment (turbolent) [inline w2c2/w2c2_base.h:194]: Given that only the suffixes differ, maybe instead of redefining all constants, we can just define and use a macro like `LL(x)` which adds the appropriate suffix?

**Review by turbolent — COMMENTED** [review]
Nice, thank you for adding support for that compiler 👍

File: w2c2/w2c2_base.h (hunk 1 above)
Comment (turbolent) [reply w2c2/w2c2_base.h]: Nice! Thank you for the refactor 👍

**Review by turbolent — APPROVED** [review]

**Comment by jamesy0ung** [comment]
Hi @SergioFLS,

I came across your PR on getting w2c2 to compile with MSVC 4.0, and I really appreciate the effort you put into it! I’ve been trying to build w2c2 and the examples using MSVC 4.0 myself, but I’ve run into several compilation errors while attempting to modify the Makefile to work with nmake.

Would you be able to share any instructions or insights on how you got it working? Any guidance would be greatly appreciated.
